import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Analytics } from "@vercel/analytics/react"

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";
import { PracticeModal } from "@/components/modals/practice-modal";
import MouseTracker from "@/components/MouseTracker";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lang.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
      <html lang="en">
        <body className={font.className}>
          <Analytics />
          <Toaster />
          <ExitModal />
          <HeartsModal />
          <MouseTracker />
          <PracticeModal />
          {children}
        </body>
      </html>
     
    </ClerkProvider>
  );
}
